# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palazzo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.SlugField()),
                ('item_name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Green', 'Green'), ('Blue', 'Blue'), ('Red', 'Red'), ('Orange', 'Orange')], max_length=30)),
                ('material', models.CharField(choices=[('Crepe', 'Crepe'), ('Cotton', 'Cotton'), ('Rayon', 'Rayon'), ('Silk', 'Silk')], max_length=30)),
                ('sp', models.IntegerField(default=399, verbose_name='Selling Price')),
                ('mrp', models.IntegerField(default=899, verbose_name='MRP')),
                ('qty', models.PositiveSmallIntegerField(default=5, verbose_name='Inventory')),
                ('description', models.TextField()),
                ('upc', models.CharField(blank=True, default='0123456789', max_length=14)),
                ('weight', models.FloatField(verbose_name='Product Weight')),
                ('weight_unit', models.CharField(choices=[('kg', 'kg'), ('gm', 'gm')], max_length=5)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10)),
                ('key_feature1', models.CharField(default='Wide Leg Pants', max_length=50)),
                ('key_feature2', models.CharField(default='Single Side Pocket', max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='palazzo_img')),
            ],
        ),
    ]
