# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='palazzo',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='palazzo',
            name='weight',
            field=models.FloatField(default=0.25, verbose_name='Product Weight'),
        ),
        migrations.AlterField(
            model_name='palazzo',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('gm', 'gm')], default='kg', max_length=5),
        ),
    ]
