# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0002_auto_20171122_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
