# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0005_auto_20171124_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palazzo',
            name='img',
            field=models.ImageField(blank=True, default='/palazzo_img/optimus.jpg', null=True, upload_to='palazzo_img'),
        ),
    ]
