# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0006_auto_20171125_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(upload_to='palazzo_img')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipkart.Palazzo')),
            ],
        ),
    ]
